musicApp/albums/urls.py
from django.urls import path

from albums import views

app_name = 'albums'

urlpatterns = [
    path('create/', views.AlbumCreateView.as_view(), name='create'),
    path('details/<int:pk>/', views.AlbumDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.AlbumEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.AlbumDeleteView.as_view(), name='delete'),
]

musicApp/musicApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('albums/', include('albums.urls')),
]

musicApp/profiles/urls.py
from django.urls import path
from profiles import views

app_name = 'profiles'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('details/', views.ProfileDetailView.as_view(), name='detail'),
    path('delete/', views.ProfileDeleteView.as_view(), name='delete')
]

musicApp/albums/models.py
from django.core.validators import MinLengthValidator, RegexValidator, MinValueValidator
from django.db import models


class Album(models.Model):
    class Genre(models.TextChoices):
        POP_MUSIC = 'Pop Music', 'Pop Music'
        JAZZ_MUSIC = 'Jazz Music', 'Jazz Music'
        RB_MUSIC = 'R&B Music', 'R&B Music'
        ROCK_MUSIC = 'Rock Music', 'Rock Music'
        COUNTRY_MUSIC = 'Country Music', 'Country Music'
        DANCE_MUSIC = 'Dance Music', 'Dance Music'
        HIP_HOP_MUSIC = 'Hip Hop Music', 'Hip Hop Music'
        OTHER = 'Other', 'Other'

    album_name = models.CharField(
        max_length=30,
        unique=True,
    )

    artist = models.CharField(
        max_length=30,
    )

    genre = models.CharField(
        max_length=30,
        choices=Genre.choices,
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    image_url = models.URLField()

    price = models.FloatField(
        validators=[
            MinValueValidator(
                limit_value=0,
            )
        ]
    )

    owner = models.ForeignKey(
        "profiles.Profile",
        on_delete=models.CASCADE,
        related_name="albums",
    )

musicApp/profiles/models.py
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models


class Profile(models.Model):
    username = models.CharField(
        max_length=15,
        validators=[
            MinLengthValidator(2),
            RegexValidator(
                regex=r'^[A-Za-z0-9_]+$',
                message='Ensure this value contains only letters, numbers, and underscore.',
            )
        ]
    )

    email = models.EmailField()

    age = models.PositiveIntegerField(
        blank=True,
        null=True,
    )

musicApp/albums/forms.py
from django import forms
from albums.models import Album


class AlbumBaseForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = '__all__'
        widgets = {
            'album_name': forms.TextInput(attrs={'placeholder': 'Album Name'}),
            'artist': forms.TextInput(attrs={'placeholder': 'Artist'}),
            'description': forms.Textarea(attrs={'placeholder': 'Description'}),
            'image_url': forms.URLInput(attrs={'placeholder': 'Image URL'}),
            'price': forms.NumberInput(attrs={'placeholder': 'Price'}),
            'owner': forms.HiddenInput(),
        }


class AlbumCreateForm(AlbumBaseForm):
    ...


class AlbumEditForm(AlbumBaseForm):
    ...


class AlbumDeleteForm(AlbumBaseForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['readonly'] = True
            field.widget.attrs['disabled'] = True

musicApp/profiles/forms.py
from django import forms
from profiles.models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"
        widgets = {
            "username": forms.TextInput(
                attrs={'placeholder': 'Username'},
            ),
            "email": forms.EmailInput(
                attrs={'placeholder': 'Email'},
            ),
            "age": forms.NumberInput(
                attrs={'placeholder': 'Age'},
            )
        }

musicApp/albums/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from albums.forms import AlbumCreateForm, AlbumEditForm, AlbumDeleteForm
from albums.mixins import AttachOwnerMixin
from albums.models import Album
from profiles.util import get_profile


class AlbumCreateView(AttachOwnerMixin, CreateView):
    model = Album
    form_class = AlbumCreateForm
    success_url = reverse_lazy("profiles:home")
    template_name = 'albums/album-add.html'


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'albums/album-details.html'


class AlbumEditView(AttachOwnerMixin, UpdateView):
    model = Album
    form_class = AlbumEditForm
    template_name = 'albums/album-edit.html'

    def get_success_url(self) -> str:
        return reverse('albums:detail', kwargs={'pk': self.object.pk})


class AlbumDeleteView(DeleteView):
    model = Album
    form_class = AlbumDeleteForm
    template_name = 'albums/album-delete.html'
    success_url = reverse_lazy("profiles:home")

    def get_initial(self) -> dict:
        return self.object.__dict__

    def form_invalid(self, form):
        return super().form_valid(form)

musicApp/profiles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import DetailView, TemplateView

from albums.models import Album
from profiles.forms import ProfileForm
from profiles.models import Profile
from profiles.util import get_profile


class HomeView(View):
    def get(self, request) -> HttpResponse:
        profile = get_profile()

        context = {
            "form": ProfileForm(),
        }

        if not profile:
            return render(request, 'profiles/home-no-profile.html', context)

        all_albums = Album.objects.all()
        context["albums"] = all_albums

        return render(request, 'profiles/home-with-profile.html', context)

    def post(self, request) -> HttpResponse:
        form = ProfileForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("profiles:home")  # Todo: redirect to profile page

        return render(request, 'profiles/home-no-profile.html', {"form": form})


class ProfileDetailView(DetailView):
    template_name = 'profiles/profile-details.html'

    def get_object(self, queryset=None) -> Profile:
        return get_profile()

    def get_context_data(self, **kwargs) -> dict:
        kwargs.update({
            "albums_count": self.object.albums.count(),
        })
        return super().get_context_data(**kwargs)


class ProfileDeleteView(TemplateView):
    template_name = 'profiles/profile-delete.html'

    def post(self, request):
        get_profile().delete()
        return redirect('profiles:home')

musicApp/templates/common/footer.html
<!-- Footer -->
<footer>
    <div>&copy;SoftUni Team. All rights reserved.</div>
</footer>
<!-- End Footer -->

musicApp/templates/common/nav.html
{% load static %}

<header>
<nav>
  <img src="{% static 'images/headphones.png' %}" alt="headphones" />
  <a href="#">Home</a>
  <ul></ul>
  <ul>
    <!--Only for user with created profile-->
    <li><a href="{% url 'albums:create' %}">Create Album</a></li>
    <li><a href="{% url 'profiles:detail' %}">Profile</a></li>
  </ul>
</nav>
</header>

musicApp/templates/profiles/home-no-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-inline">
<section id="welcomePage">
  <div id="welcome-message">
    <h1>Welcome to</h1>
    <h1>My Music App!</h1>
  </div>
  <div class="music-img">
    <img src="{% static 'images/musicIcons.webp' %}" alt="music-icon" />
  </div>
</section>

<!-- Registration -->
<section id="registerPage">
  <form method="post">
    <fieldset>
      <legend>Profile</legend>
        {{ form }}
      {% csrf_token %}
      <button type="submit" class="register">Enter</button>
    </fieldset>
  </form>
</section>
</div>
{% endblock %}

musicApp/templates/profiles/home-with-profile.html
{% extends 'base.html' %}

{% block content %}
<section id="catalogPage">

{% if albums %}
    <h1>All Albums</h1>
{% else %}
    <p>No albums</p>
{% endif %}

{% for album in albums %}
    <div class="card-box">
      <img src="{{ album.image_url }}" alt="Cover Image" />
      <div>
        <div class="text-center">
          <p class="name">Name: {{ album.album_name }}</p>
          <p class="artist">Artist: {{ album.artist }}</p>
          <p class="genre">Genre: {{ album.genre }}</p>
          <p class="price">Price: ${{ album.price|floatformat:2 }}</p>
        </div>
        <div class="btn-group">
          <a href="{% url 'albums:detail' album.pk %}">Details</a>
        </div>
      </div>
    </div>
{% empty %}

{% endfor %}
</section>
{% endblock %}

musicApp/templates/profiles/profile-delete.html
{% extends 'base.html' %}

{% block content %}
<section id="detailsPage">
    <div class="wrapper">
      <div class="profileText">
        <!-- Delete Profile Form -->
        <h1>Are you sure you want to delete your profile?</h1>
        <form method="post">
          <!-- Confirm Button -->
            {% csrf_token %}
          <button class="delete-profile" type="submit">Delete</button>
        </form>
        <!-- End Delete Profile Form -->
      </div>
    </div>
</section>
{% endblock %}

musicApp/templates/profiles/profile-details.html
{% extends 'base.html' %}

{% block content %}
<section id="detailsPage">
    <div class="wrapper">
      <div class="profilePage">
        <img
          src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
          alt="Profile Image"
        />
      </div>
    
      <div class="profileText">
        <!-- Profile Info -->
        <h1>Username: {{ object.username }}</h1>
        <h1>Email: {{ object.email }}</h1>
        <h1>Age: {{ object.age }}</h1>
        <h1>Albums: {{ albums_count }}</h1>
      </div>
    
      <div class="actionBtn">
        <!-- Button for Deleting the Profile -->
        <a href="{% url 'profiles:delete' %}" class="remove">Delete</a>
      </div>
    </div>
</section>
{% endblock %}